=== NCEAS/semtools/dev/sms/sms-semannot.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	   targetNamespace="http://ecoinformatics.org/sms/annotation.1.0beta1"
	   xmlns="http://ecoinformatics.org/sms/annotation.1.0beta1"
	   xmlns:party="eml://ecoinformatics.org/party-2.1.1"
	   xmlns:res="eml://ecoinformatics.org/resource-2.1.1"
	   elementFormDefault="qualified">
<xs:import namespace="eml://ecoinformatics.org/party-2.1.1" schemaLocation="https://code.ecoinformatics.org/code/eml/tags/RELEASE_EML_2_1_1_RC_2/eml-party.xsd"/>
<xs:import namespace="eml://ecoinformatics.org/resource-2.1.1" schemaLocation="https://code.ecoinformatics.org/code/eml/tags/RELEASE_EML_2_1_1_RC_2/eml-resource.xsd"/>

  <!-- annotations -->
  <xs:complexType name="AnnotationType">
    <xs:sequence minOccurs="0">
		<xs:element name="observation" type="ObservationType" maxOccurs="unbounded"/>
		<xs:element name="map" type="MapType" minOccurs="0" maxOccurs="unbounded"/>
		<xs:element name="creator" type="party:ResponsibleParty" minOccurs="0"/>
		<xs:element name="createDate" type="res:yearDate" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="dataPackage" type="xs:string" use="required"/>
  </xs:complexType>


  <!-- observations -->
  <xs:complexType name="ObservationType">
    <xs:sequence>
      <xs:element name="entity" type="EntityType" minOccurs="0" maxOccurs="1"/>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
		<xs:choice>
		  <xs:element name="measurement" type="MeasurementType"/>
		  <xs:element name="context" type="ContextType"/>
		</xs:choice>
      </xs:sequence>
    </xs:sequence>
    <xs:attribute name="label" type="xs:ID" use="optional"/>
    <xs:attribute name="distinct" type="xs:string" default="no"/>
  </xs:complexType>


  <!-- measurements --> 
  <xs:complexType name="MeasurementType">
    <xs:sequence>
		<xs:element name="characteristic" type="CharacteristicType" 
			minOccurs="0" maxOccurs="unbounded"/>
		<xs:element name="standard" type="StandardType"
			minOccurs="0" maxOccurs="1"/>
		<xs:element name="protocol" type="ProtocolType"
			minOccurs="0" maxOccurs="1"/>	
		<xs:element name="domain" type="DomainType" 
			minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:QName" use="optional"/>
    <xs:attribute name="label" type="xs:ID" use="optional"/>
    <xs:attribute name="precision" type="xs:float" use="optional"/>
    <xs:attribute name="value" type="xs:string" use="optional"/>
    <xs:attribute name="key" type="xs:string" default="no"/>
  </xs:complexType>


  <!-- entities --> 
  <xs:complexType name="EntityType">
    <xs:attribute name="id" type="xs:QName" use="required"/>
  </xs:complexType>


  <!-- characteristics --> 
  <xs:complexType name="CharacteristicType">
    <xs:attribute name="id" type="xs:QName" use="required"/>
    <xs:attribute name="value" type="xs:string" use="optional"/>
  </xs:complexType>


  <!-- standards --> 
  <xs:complexType name="StandardType">
    <xs:attribute name="id" type="xs:QName" use="required"/>
  </xs:complexType>

  <!-- protocol --> 
  <xs:complexType name="ProtocolType">
    <xs:attribute name="id" type="xs:QName" use="required"/>
  </xs:complexType>
  
  <!-- domains --> 
  <xs:complexType name="DomainType">
    <xs:sequence>
       <xs:element name="entity" type="EntityType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="min" type="xs:string" use="optional"/>
    <xs:attribute name="max" type="xs:string" use="optional"/>
  </xs:complexType>


  <!-- contexts --> 
  <xs:complexType name="ContextType">
    <xs:sequence>
      <xs:element name="relationship" type="RelationshipType"
		  minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="observation" type="xs:IDREF" use="required"/>
    <xs:attribute name="identifying" type="xs:string" default="no"/>
  </xs:complexType>


  <!-- relationships --> 
  <xs:complexType name="RelationshipType">
    <xs:attribute name="id" type="xs:QName" use="required"/>
  </xs:complexType>


  <!-- mappings --> 
  <xs:complexType name="MapType">
    <xs:attribute name="dataObject" type="xs:string" use="required"/>
    <xs:attribute name="attribute" type="xs:string" use="required"/>
    <xs:attribute name="measurement" type="xs:IDREF" use="required"/>
    <xs:attribute name="value" type="xs:string" use="optional"/>
    <xs:attribute name="if" type="xs:string" use="optional"/>
  </xs:complexType>


  <!-- annotation element --> 
  <xs:element name="annotation" type="AnnotationType"/>


</xs:schema>

=== NCEAS/semtools/dev/sms/examples/Salmon/cjones-annotation.20.1.xml
<?xml version="1.0"?>
<sms:annotation 
  xmlns:sms="http://ecoinformatics.org/sms/annotation.1.0beta1" 
  xmlns:oboe-characteristics="http://ecoinformatics.org/oboe/oboe.1.0/oboe-characteristics.owl#" 
  xmlns:oboe-standards="http://ecoinformatics.org/oboe/oboe.1.0/oboe-standards.owl#" 
  xmlns:oboe-temporal="http://ecoinformatics.org/oboe/oboe.1.0/oboe-temporal.owl#" 
  xmlns:oboe-spatial="http://ecoinformatics.org/oboe/oboe.1.0/oboe-spatial.owl#" 
  xmlns:oboe-salmon="http://ecoinformatics.org/oboe-ext/salmon.1.0/oboe-salmon.owl#" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://ecoinformatics.org/sms/annotation.1.0beta1 http://ecoinformatics.org/sms/annotation.1.0beta1/sms-semannot.xsd" 
  id="cjones.20.1" 
  dataPackage="cjones.21.1">
  
  <!-- Observation: TimeInstant (trap set)-->
  <sms:observation label="o1">
    <sms:entity id="oboe-temporal:TimeInstant"/>
    <sms:measurement label="m1a">
      <sms:characteristic id="oboe-characteristics:Time" />
      <sms:standard id="oboe-standards:Day" />
    </sms:measurement>
    <sms:measurement label="m1b">
      <sms:characteristic id="oboe-characteristics:Time" />
      <sms:standard id="oboe-standards:Minute" />
    </sms:measurement>
  </sms:observation>

  <!-- Observation: TimeInstant (trap check)-->
  <sms:observation label="o2">
    <sms:entity id="oboe-temporal:TimeInstant"/>
    <sms:measurement label="m2a">
      <sms:characteristic id="oboe-characteristics:Time" />
      <sms:standard id="oboe-standards:Day" />
    </sms:measurement>
    <sms:measurement label="m2b">
      <sms:characteristic id="oboe-characteristics:Time" />
      <sms:standard id="oboe-standards:Minute" />
    </sms:measurement>
  </sms:observation>

  <!-- Observation: AliveSmoltSteelheadPopulationSample -->
  <sms:observation label="o3">
    <sms:entity id="oboe-salmon:AliveSmoltSteelheadPopulationSample"/>
    <sms:measurement label="m3">
      <sms:characteristic id="oboe-characteristics:Count" />
      <sms:standard id="oboe-standards:Number" />
    </sms:measurement>
  </sms:observation>
  
  <!-- Observation: DeadSmoltSteelheadPopulationSample -->
  <sms:observation label="o4">
    <sms:entity id="oboe-salmon:DeadSmoltSteelheadPopulationSample"/>
    <sms:measurement label="m4">
      <sms:characteristic id="oboe-characteristics:Count" />
      <sms:standard id="oboe-standards:Number" />
    </sms:measurement>
  </sms:observation>
  
  <!-- Observation: AliveParrSteelheadPopulationSample -->
  <sms:observation label="o5">
    <sms:entity id="oboe-salmon:AliveSmoltSteelheadPopulationSample"/>
    <sms:measurement label="m5">
      <sms:characteristic id="oboe-characteristics:Count" />
      <sms:standard id="oboe-standards:Number" />
    </sms:measurement>
  </sms:observation>
  
  <!-- Observation: DeadParrSteelheadPopulationSample -->
  <sms:observation label="o6">
    <sms:entity id="oboe-salmon:DeadSmoltSteelheadPopulationSample"/>
    <sms:measurement label="m6">
      <sms:characteristic id="oboe-characteristics:Count" />
      <sms:standard id="oboe-standards:Number" />
    </sms:measurement>
  </sms:observation>
  
  <!-- Observation: AliveSpringChinookPopulationSample -->
  <sms:observation label="o7">
    <sms:entity id="oboe-salmon:AliveSpringChinookPopulationSample"/>
    <sms:measurement label="m7">
      <sms:characteristic id="oboe-characteristics:Count" />
      <sms:standard id="oboe-standards:Number" />
    </sms:measurement>
  </sms:observation>
  
  <!-- Observation: DeadSpringChinookPopulationSample -->
  <sms:observation label="o8">
    <sms:entity id="oboe-salmon:DeadSpringChinookPopulationSample"/>
    <sms:measurement label="m8">
      <sms:characteristic id="oboe-characteristics:Count" />
      <sms:standard id="oboe-standards:Number" />
    </sms:measurement>
  </sms:observation>
  
  <!-- Mapping: TimeInstant -->
  <sms:map dataObject="1" attribute="trap_set_date" measurement="m1a" />
  <sms:map dataObject="1" attribute="trap_set_time" measurement="m1b" />
  <sms:map dataObject="1" attribute="trap_check_date" measurement="m2a" />
  <sms:map dataObject="1" attribute="trap_check_time" measurement="m2b" />
  
  <!-- Mapping: AliveSmoltSteelheadPopulationSample -->
  <sms:map dataObject="1" attribute="live_wild_stlhd_smolts" measurement="m3" />
  
  <!-- Mapping: DeadSmoltSteelheadPopulationSample -->
  <sms:map dataObject="1" attribute="dead_wild_stlhd_smolts" measurement="m4" />
  
  <!-- Mapping: AliveParrSteelheadPopulationSample -->
  <sms:map dataObject="1" attribute="live_wild_stlhd_parr" measurement="m5" />
  
  <!-- Mapping: DeadParrSteelheadPopulationSample -->
  <sms:map dataObject="1" attribute="dead_wild_stlhd_parr" measurement="m6" />

  <!-- Mapping: AliveSpringChinookPopulationSample -->
  <sms:map dataObject="1" attribute="live_wild_spring_chnk" measurement="m7" />
  
  <!-- Mapping: DeadSpringChinookPopulationSample -->
  <sms:map dataObject="1" attribute="dead_wild_spring_chnk" measurement="m8" />
  
</sms:annotation>

=== NCEAS/semtools/dev/sms/examples/er-2008-ex1-annot.xml
<?xml version="1.0"?>
<sms:annotation 
  xmlns="http://ecoinformatics.org/sms/annotation.0.9"
  xmlns:ont1="http://linus.nceas.ucsb.edu/sms/metacat/ont.3.1"
  xmlns:ont2="http://linus.nceas.ucsb.edu/sms/metacat/ont.5.1"
  xmlns:ont3="http://linus.nceas.ucsb.edu/sms/metacat/ont.6.1"
  xmlns:sms="http://ecoinformatics.org/sms/annotation.0.9"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://ecoinformatics.org/sms/annotation.0.9 sms-semannot.xsd"
  emlPackage="eml.1.1" dataTable="1">
    <sms:observation label="o1" distinct="yes">
        <sms:entity id="ont3:TemporalRange"/>
        <sms:measurement label="m1" key="yes">
            <sms:characteristic id="ont3:Year"/>
            <sms:standard id="ont1:DateTime"/>
        </sms:measurement>
    </sms:observation>
    <sms:observation label="o2">
        <sms:entity id="ont3:Tree"/>
        <sms:measurement label="m2" precision="0.1">
            <sms:characteristic id="ont3:DBH"/>
            <sms:standard id="ont2:Centimeter"/>
        </sms:measurement>
        <sms:measurement label="m3">
            <sms:characteristic id="ont3:TaxonomicTypeName"/>
            <sms:standard id="ont3:ITIS"/>
        </sms:measurement>
        <sms:measurement label="m4" key="yes">
            <sms:characteristic id="ont1:EntityName"/>
            <sms:standard id="ont3:LocalTreeNames"/>
        </sms:measurement>
        <sms:context observation="o1">
            <sms:relationship id="ont3:Within"/>
        </sms:context>
    </sms:observation>
    <sms:map attribute="yr" measurement="m1"/>
    <sms:map attribute="diam" measurement="m2" if="diam ge 0"/>
    <sms:map attribute="tree" measurement="m3"/>
    <sms:map attribute="spp" measurement="m4" value="Picea rubens" 
	   if="spp eq 'piru'"/>
    <sms:map attribute="spp" measurement="m4" value="Abies balsamea" 
	   if="spp eq 'abba'"/>
</sms:annotation>

=== NCEAS/semtools/dev/sms/examples/er-2008-ex3-annot.xml
<?xml version="1.0"?>
<sms:annotation 
	xmlns="http://ecoinformatics.org/sms/annotation.0.9"
	xmlns:ont1="http://linus.nceas.ucsb.edu/sms/metacat/ont.3.1"
	xmlns:ont2="http://linus.nceas.ucsb.edu/sms/metacat/ont.5.1"
	xmlns:ont3="http://linus.nceas.ucsb.edu/sms/metacat/ont.6.1"
	xmlns:sms="http://ecoinformatics.org/sms/annotation.0.9"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ecoinformatics.org/sms/annotation.0.9 sms-semannot.xsd"
	emlPackage="eml.3.1" dataTable="1">

  <!-- Water-Treatment Observation -->
    <sms:observation label="o1" distinct="yes">
        <sms:entity id="ont3:FreshWater"/>
        <sms:measurement label="m1" key="yes">
            <sms:characteristic id="ont1:Depth"/>
            <sms:standard id="ont3:LocalTreatmentWaterDepths"/>
        </sms:measurement>
    </sms:observation>

  <!-- Transect Observation -->
    <sms:observation label="o2" distinct="yes">
        <sms:entity id="ont3:Transect"/>
        <sms:measurement label="m2" key="yes">
            <sms:characteristic id="ont1:EntityName"/>
            <sms:standard id="ont3:LocalTransectIds"/>
        </sms:measurement>
        <sms:context observation="o1">
            <sms:relationship id="ont3:Within"/>
        </sms:context>
    </sms:observation>

  <!-- Soil Observation -->
    <sms:observation label="o3">
        <sms:entity id="ont3:Soil"/>
        <sms:measurement label="m3" key="yes">
            <sms:characteristic id="ont3:SoilTypeName"/>
            <sms:standard id="ont3:StandardSoilTypes"/>
        </sms:measurement>
        <sms:measurement label="m4" precision="0.1">
            <sms:characteristic id="ont3:Acidity"/>
            <sms:standard id="ont3:pH"/>
        </sms:measurement>
        <sms:context observation="o2" identifying="yes">
            <sms:relationship id="ont3:Overlaps"/>
        </sms:context>
        <sms:context observation="o4">
            <sms:relationship id="ont3:Contains"/>
        </sms:context>
    </sms:observation>

  <!-- Tree Observation -->
    <sms:observation label="o4" distinct="yes">
        <sms:entity id="ont3:Tree"/>
        <sms:measurement label="m5" key="yes">
            <sms:characteristic id="ont1:EntityName"/>
            <sms:standard id="ont1:LocalTreeNames"/>
        </sms:measurement>
        <sms:measurement label="m6">
            <sms:characteristic id="ont3:TaxonomicTypeName"/>
            <sms:standard id="ont3:ITIS"/>
        </sms:measurement>
        <sms:measurement label="m7" precision="0.1">
            <sms:characteristic id="ont3:DBH"/>
            <sms:standard id="ont2:Centimeter"/>
        </sms:measurement>
        <sms:context observation="o2">
            <sms:relationship id="ont3:Near"/>
        </sms:context>
        <sms:context observation="o3">
            <sms:relationship id="ont3:Within"/>
        </sms:context>
    </sms:observation>  
  

  <!-- attribute mappings -->
    <sms:map attribute="trns" measurement="m2"/>
    <sms:map attribute="trmt" measurement="m1"/>
    <sms:map attribute="soil" measurement="m3"/>
    <sms:map attribute="pH" measurement="m4"/>
    <sms:map attribute="tree" measurement="m5"/>
    <sms:map attribute="spp" measurement="m6" value="Picea rubens" 
	   if="spp eq 'piru'"/>
    <sms:map attribute="spp" measurement="m6" value="Abies balsamea" 
	   if="spp eq 'abba'"/>
    <sms:map attribute="dbh" measurement="m7"/>
</sms:annotation>

=== NCEAS/semtools/dev/sms/oboedb/mobrien.38.19.xml
<?xml version="1.0"?>
<sms:annotation xmlns:sms="http://ecoinformatics.org/sms/annotation.0.9" xmlns:oboe-sbc.owl="https://code.ecoinformatics.org/code/semtools/trunk/dev/oboe/oboe-sbc.owl" xmlns:oboe-gce.owl="https://code.ecoinformatics.org/code/semtools/trunk/dev/oboe/oboe-gce.owl" xmlns:oboe-units.1.0beta="http://ecoinformatics.org/oboe/oboe-units.1.0beta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ecoinformatics.org/sms/annotation.0.9 http://ecoinformatics.org/sms/annotation.0.9/sms-semannot.xsd" id="mobrien.38.19" emlPackage="mobrien.47.1" dataTable="0">
   <sms:observation label="o1">
      <sms:entity id="oboe-sbc.owl:TemporalPoint"/>
      <sms:measurement label="m1" precision="1.0">
         <sms:characteristic id="oboe-gce.owl:Day"/>
      </sms:measurement>
      <sms:measurement label="m2" precision="1.0">
         <sms:characteristic id="oboe-gce.owl:Day"/>
      </sms:measurement>
   </sms:observation>
   <sms:observation label="o3">
      <sms:entity id="oboe-sbc.owl:StreamWaterSensorSample"/>
      <sms:measurement label="m3" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:VolumetricRate"/>
         <sms:standard id="oboe-units.1.0beta:LitersPerSecond"/>
         <sms:protocol id="oboe-sbc.owl:MelackLabProtocols"/>
      </sms:measurement>
      <sms:measurement label="m4" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:Temperature"/>
         <sms:standard id="oboe-units.1.0beta:Celsius"/>
         <sms:protocol id="oboe-sbc.owl:ProtocolsByInstrumentation"/>
      </sms:measurement>
      <sms:context observation="o1">
      </sms:context>
   </sms:observation>
   <sms:map attribute="timestamp_local" measurement="m1"/>
   <sms:map attribute="timestamp_UTC" measurement="m2"/>
   <sms:map attribute="discharge_lps" measurement="m3"/>
   <sms:map attribute="water_temperature_celsius" measurement="m4"/>
</sms:annotation>

=== NCEAS/semtools/dev/sms/oboedb/mobrien.36.59.xml
<?xml version="1.0"?>
<sms:annotation xmlns:sms="http://ecoinformatics.org/sms/annotation.0.9" xmlns:oboe-sbc.owl="https://code.ecoinformatics.org/code/semtools/trunk/dev/oboe/oboe-sbc.owl" xmlns:oboe.1.0beta="http://ecoinformatics.org/oboe/oboe.1.0beta" xmlns:oboe-units.1.0beta="http://ecoinformatics.org/oboe/oboe-units.1.0beta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ecoinformatics.org/sms/annotation.0.9 http://ecoinformatics.org/sms/annotation.0.9/sms-semannot.xsd" id="mobrien.36.59" emlPackage="mobrien.50.1" dataTable="0">
   <sms:observation label="o1">
      <sms:entity id="oboe-sbc.owl:Waypoint"/>
      <sms:measurement label="m1" precision="1.0">
         <sms:characteristic id="oboe-sbc.owl:SBCSiteName"/>
         <sms:standard id="oboe-sbc.owl:SBCSiteNameCatalog"/>
      </sms:measurement>
   </sms:observation>
   <sms:observation label="o2">
      <sms:entity id="oboe-sbc.owl:TemporalPoint"/>
      <sms:measurement label="m2" precision="1.0">
         <sms:characteristic id="oboe.1.0beta:EntityName"/>
      </sms:measurement>
   </sms:observation>
   <sms:observation label="o12">
      <sms:entity id="oboe-sbc.owl:StreamWaterDiscreteSample"/>
      <sms:measurement label="m12" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:AmountOfSubstanceConcentration"/>
         <sms:standard id="oboe.1.0beta:ComplexDerivedUnit"/>
         <sms:protocol id="oboe-sbc.owl:MelackLabProtocols"/>
      </sms:measurement>
      <sms:context observation="o1">
         <sms:relationship id="oboe-sbc.owl:Within"/>
      </sms:context>
      <sms:context observation="o2">
         <sms:relationship id="oboe-sbc.owl:Within"/>
      </sms:context>
   </sms:observation>
   <sms:observation label="o3">
      <sms:entity id="oboe-sbc.owl:StreamWaterDiscreteSample"/>
      <sms:measurement label="m3" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:AmountOfSubstanceConcentration"/>
         <sms:standard id="oboe-sbc.owl:MicromolePerLiter"/>
         <sms:protocol id="oboe-sbc.owl:AmmoniumConcentrationProtocol_BenchtopSolarzano1969"/>
      </sms:measurement>
      <sms:measurement label="m4" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:AmountOfSubstanceConcentration"/>
         <sms:standard id="oboe-sbc.owl:MicromolePerLiter"/>
         <sms:protocol id="oboe-sbc.owl:NitrateNitriteConcentrationProtocol_MSIAutomated"/>
      </sms:measurement>
      <sms:measurement label="m5" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:AmountOfSubstanceConcentration"/>
         <sms:standard id="oboe-sbc.owl:MicromolePerLiter"/>
         <sms:protocol id="oboe-sbc.owl:PhosphateConcentrationProtocol_MSIAutomated"/>
      </sms:measurement>
      <sms:context observation="o1">
         <sms:relationship id="oboe-sbc.owl:Within"/>
      </sms:context>
      <sms:context observation="o2">
         <sms:relationship id="oboe-sbc.owl:Within"/>
      </sms:context>
   </sms:observation>
   <sms:observation label="o6">
      <sms:entity id="oboe-sbc.owl:StreamWaterDiscreteSample"/>
      <sms:measurement label="m6" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:AmountOfSubstanceConcentration"/>
         <sms:standard id="oboe-sbc.owl:MicromolePerLiter"/>
         <sms:protocol id="oboe-sbc.owl:MelackLabProtocols"/>
      </sms:measurement>
      <sms:measurement label="m7" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:AmountOfSubstanceConcentration"/>
         <sms:standard id="oboe-sbc.owl:MicromolePerLiter"/>
         <sms:protocol id="oboe-sbc.owl:MelackLabProtocols"/>
      </sms:measurement>
      <sms:context observation="o1">
         <sms:relationship id="oboe-sbc.owl:Within"/>
      </sms:context>
      <sms:context observation="o2">
         <sms:relationship id="oboe-sbc.owl:Within"/>
      </sms:context>
   </sms:observation>
   <sms:observation label="o8">
      <sms:entity id="oboe-sbc.owl:StreamWaterDiscreteSample"/>
      <sms:measurement label="m8" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:AmountOfSubstanceConcentration"/>
         <sms:standard id="oboe-sbc.owl:MicromolePerLiter"/>
         <sms:protocol id="oboe-sbc.owl:SuspendedParticulateCarbonNitrogen_CHNElementalAnalyzer"/>
      </sms:measurement>
      <sms:measurement label="m10" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:AmountOfSubstanceConcentration"/>
         <sms:standard id="oboe-sbc.owl:MicromolePerLiter"/>
         <sms:protocol id="oboe-sbc.owl:SuspendedParticulatePhosphorus_AcidDigestion"/>
      </sms:measurement>
      <sms:measurement label="m11" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:AmountOfSubstanceConcentration"/>
         <sms:standard id="oboe-units.1.0beta:MolePerCubicMeter"/>
         <sms:protocol id="oboe-sbc.owl:ProtocolsByConstituent"/>
      </sms:measurement>
      <sms:measurement label="m9" precision="1.0">
         <sms:characteristic id="oboe-units.1.0beta:AmountOfSubstanceConcentration"/>
         <sms:standard id="oboe-sbc.owl:MicromolePerLiter"/>
         <sms:protocol id="oboe-sbc.owl:SuspendedParticulateCarbonNitrogen_CHNElementalAnalyzer"/>
      </sms:measurement>
      <sms:context observation="o1">
         <sms:relationship id="oboe-sbc.owl:Within"/>
      </sms:context>
      <sms:context observation="o1">
         <sms:relationship id="oboe-sbc.owl:Within"/>
      </sms:context>
   </sms:observation>
   <sms:map attribute="site_code" measurement="m1"/>
   <sms:map attribute="timestamp_local" measurement="m2"/>
   <sms:map attribute="NH4_uM" measurement="m3"/>
   <sms:map attribute="NO3_uM" measurement="m4"/>
   <sms:map attribute="PO4_uM" measurement="m5"/>
   <sms:map attribute="TDN_uM" measurement="m6"/>
   <sms:map attribute="TDP_uM" measurement="m7"/>
   <sms:map attribute="TPC_uM" measurement="m8"/>
   <sms:map attribute="TPN_uM" measurement="m9"/>
   <sms:map attribute="TPP_uM" measurement="m10"/>
   <sms:map attribute="TSS_mg/L" measurement="m11"/>
   <sms:map attribute="Spec_Cond_uS/cm" measurement="m12"/>
</sms:annotation>
