=== NCEAS/semtools/dev/sms/sms-semannot.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	   targetNamespace="http://ecoinformatics.org/sms/annotation.1.0beta1"
	   xmlns="http://ecoinformatics.org/sms/annotation.1.0beta1"
	   xmlns:party="eml://ecoinformatics.org/party-2.1.1"
	   xmlns:res="eml://ecoinformatics.org/resource-2.1.1"
	   elementFormDefault="qualified">
<xs:import namespace="eml://ecoinformatics.org/party-2.1.1" schemaLocation="https://code.ecoinformatics.org/code/eml/tags/RELEASE_EML_2_1_1_RC_2/eml-party.xsd"/>
<xs:import namespace="eml://ecoinformatics.org/resource-2.1.1" schemaLocation="https://code.ecoinformatics.org/code/eml/tags/RELEASE_EML_2_1_1_RC_2/eml-resource.xsd"/>

  <!-- annotations -->
  <xs:complexType name="AnnotationType">
    <xs:sequence minOccurs="0">
		<xs:element name="observation" type="ObservationType" maxOccurs="unbounded"/>
		<xs:element name="map" type="MapType" minOccurs="0" maxOccurs="unbounded"/>
		<xs:element name="creator" type="party:ResponsibleParty" minOccurs="0"/>
		<xs:element name="createDate" type="res:yearDate" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="dataPackage" type="xs:string" use="required"/>
  </xs:complexType>


  <!-- observations -->
  <xs:complexType name="ObservationType">
    <xs:sequence>
      <xs:element name="entity" type="EntityType" minOccurs="0" maxOccurs="1"/>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
		<xs:choice>
		  <xs:element name="measurement" type="MeasurementType"/>
		  <xs:element name="context" type="ContextType"/>
		</xs:choice>
      </xs:sequence>
    </xs:sequence>
    <xs:attribute name="label" type="xs:ID" use="optional"/>
    <xs:attribute name="distinct" type="xs:string" default="no"/>
  </xs:complexType>


  <!-- measurements --> 
  <xs:complexType name="MeasurementType">
    <xs:sequence>
		<xs:element name="characteristic" type="CharacteristicType" 
			minOccurs="0" maxOccurs="unbounded"/>
		<xs:element name="standard" type="StandardType"
			minOccurs="0" maxOccurs="1"/>
		<xs:element name="protocol" type="ProtocolType"
			minOccurs="0" maxOccurs="1"/>	
		<xs:element name="domain" type="DomainType" 
			minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:QName" use="optional"/>
    <xs:attribute name="label" type="xs:ID" use="optional"/>
    <xs:attribute name="precision" type="xs:float" use="optional"/>
    <xs:attribute name="value" type="xs:string" use="optional"/>
    <xs:attribute name="key" type="xs:string" default="no"/>
  </xs:complexType>


  <!-- entities --> 
  <xs:complexType name="EntityType">
    <xs:attribute name="id" type="xs:QName" use="required"/>
  </xs:complexType>


  <!-- characteristics --> 
  <xs:complexType name="CharacteristicType">
    <xs:attribute name="id" type="xs:QName" use="required"/>
    <xs:attribute name="value" type="xs:string" use="optional"/>
  </xs:complexType>


  <!-- standards --> 
  <xs:complexType name="StandardType">
    <xs:attribute name="id" type="xs:QName" use="required"/>
  </xs:complexType>

  <!-- protocol --> 
  <xs:complexType name="ProtocolType">
    <xs:attribute name="id" type="xs:QName" use="required"/>
  </xs:complexType>
  
  <!-- domains --> 
  <xs:complexType name="DomainType">
    <xs:sequence>
       <xs:element name="entity" type="EntityType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="min" type="xs:string" use="optional"/>
    <xs:attribute name="max" type="xs:string" use="optional"/>
  </xs:complexType>


  <!-- contexts --> 
  <xs:complexType name="ContextType">
    <xs:sequence>
      <xs:element name="relationship" type="RelationshipType"
		  minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="observation" type="xs:IDREF" use="required"/>
    <xs:attribute name="identifying" type="xs:string" default="no"/>
  </xs:complexType>


  <!-- relationships --> 
  <xs:complexType name="RelationshipType">
    <xs:attribute name="id" type="xs:QName" use="required"/>
  </xs:complexType>


  <!-- mappings --> 
  <xs:complexType name="MapType">
    <xs:attribute name="dataObject" type="xs:string" use="required"/>
    <xs:attribute name="attribute" type="xs:string" use="required"/>
    <xs:attribute name="measurement" type="xs:IDREF" use="required"/>
    <xs:attribute name="value" type="xs:string" use="optional"/>
    <xs:attribute name="if" type="xs:string" use="optional"/>
  </xs:complexType>


  <!-- annotation element --> 
  <xs:element name="annotation" type="AnnotationType"/>


</xs:schema>

=== NCEAS/semtools/dev/sms/examples/inv-gcem-0501a2-1-0-annot.xml
<?xml version="1.0"?>
<sms:annotation
   xmlns="http://ecoinformatics.org/sms/annotation.0.9"
   xmlns:sms="http://ecoinformatics.org/sms/annotation.0.9"
   xmlns:oboe="https://code.ecoinformatics.org/code/semtools/trunk/dev/oboe/oboe.owl"
   xmlns:unit="https://code.ecoinformatics.org/code/semtools/trunk/dev/oboe/oboe-unit.owl"
   xmlns:gce="https://code.ecoinformatics.org/code/semtools/trunk/dev/oboe/oboe-gce.owl"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://ecoinformatics.org/sms/annotation.0.9 sms-semannot.xsd"
   emlPackage="eml.4.1"
   dataTable="1">

  <!-- observation: Spatial Location -->
   <sms:observation label="o1" distinct="yes">
      <sms:entity id="gce:SpatialLocation"/>
      <sms:measurement label="m1" key="yes">
         <sms:characteristic id="oboe:EntityName"/>
         <sms:standard id="gce:GCESiteNames"/>
         <sms:domain>
            <entity id="gce:Eulonia"/>
            <entity id="gce:FourMileIsland"/>
            <entity id="gce:NorthSapelo"/>
            <entity id="gce:Meridian"/>
            <entity id="gce:FollyRiver"/>
            <entity id="gce:DeanCreek"/>
            <entity id="gce:CarrsIsland"/>
            <entity id="gce:AlligatorCreek"/>
            <entity id="gce:RockdedundyIsland"/>
            <entity id="gce:HuntCamp"/>
         </sms:domain>
      </sms:measurement>
   </sms:observation>

  <!-- mapping: Spatial Location -->
   <sms:map attribute="att.4" measurement="m1"
      if="att.4 eq 1" value="GCE1"/>
   <sms:map attribute="att.4" measurement="m1"
      if="att.4 eq 2" value="GCE2"/>
   <sms:map attribute="att.4" measurement="m1"
      if="att.4 eq 3" value="GCE3"/>
   <sms:map attribute="att.4" measurement="m1"
      if="att.4 eq 4" value="GCE4"/>
   <sms:map attribute="att.4" measurement="m1"
      if="att.4 eq 5" value="GCE5"/>
   <sms:map attribute="att.4" measurement="m1"
      if="att.4 eq 6" value="GCE6"/>
   <sms:map attribute="att.4" measurement="m1"
      if="att.4 eq 7" value="GCE7"/>
   <sms:map attribute="att.4" measurement="m1"
      if="att.4 eq 8" value="GCE8"/>
   <sms:map attribute="att.4" measurement="m1"
      if="att.4 eq 9" value="GCE9"/>
   <sms:map attribute="att.4" measurement="m1"
      if="att.4 eq 10" value="GCE10"/>


  <!-- observation: Temporal Point -->
   <sms:observation label="o2" distinct="yes">
      <sms:entity id="gce:TemporalPoint"/>
      <sms:measurement label="m2a" key="yes">
         <sms:characteristic id="gce:Year"/>
         <sms:standard id="gce:DateTimeYYYY"/>
      </sms:measurement>
      <sms:measurement label="m2b" key="yes">
         <sms:characteristic id="gce:Month"/>
         <sms:standard id="gce:DateTimeMM"/>
      </sms:measurement>
      <sms:measurement label="m2c" key="yes">
         <sms:characteristic id="gce:Day"/>
         <sms:standard id="gce:DateTimeDD"/>
      </sms:measurement>
   </sms:observation>

  <!-- mapping: Temporal Point -->
   <sms:map attribute="att.1" measurement="m2a"/>
   <sms:map attribute="att.2" measurement="m2b"/>
   <sms:map attribute="att.3" measurement="m2c"/>

   
  <!-- observation: Zone -->
   <sms:observation label="o3" distinct="yes">
      <sms:entity id="gce:Zone"/>
      <sms:measurement label="m3" key="yes">
         <sms:characteristic id="oboe:EntityType"/>
         <sms:standard id="gce:ZoneTypeNames"/>
         <sms:domain>
            <entity id="gce:CreekBankZone"/>
            <entity id="gce:HighMarshZone"/>
         </sms:domain>
      </sms:measurement>
   </sms:observation>

  <!-- mapping: Zone -->
   <sms:map attribute="att.5" measurement="m3"
      if="att.5 eq 1" value="CreekBank"/>
   <sms:map attribute="att.5" measurement="m3"
      if="att.5 eq 2" value="HighMarsh"/>


  <!-- observation: ReplicatePlot -->
   <sms:observation label="o4" distinct="yes">
      <sms:entity id="gce:ReplicatePlot"/>
      <sms:measurement label="m4a" key="yes">
         <sms:characteristic id="oboe:EntityName"/>
         <sms:standard id="oboe:Nominal"/>
      </sms:measurement>
      <sms:context observation="o1" identifying="yes">
         <sms:relationship id="gce:Within"/>
      </sms:context>
      <sms:context observation="o3" identifying="yes">
         <sms:relationship id="gce:Within"/>
      </sms:context>
   </sms:observation>
   
  <!-- mapping: ReplicatePlot -->
   <sms:map attribute="att.6" measurement="m4a"/>


  <!-- observation: Mollusc -->
   <sms:observation label="o5" distinct="no">
      <sms:entity id="gce:Mollusc"/>
      <sms:measurement label="m5a" key="no">
         <sms:characteristic id="oboe:EntityType"/>
         <sms:standard id="gce:PopulationTypeNames"/>
         <sms:domain>
            <entity id="gce:LittorariaIrrorata"/>
            <entity id="gce:MelampusBidentatus"/>
            <entity id="gce:DetraciaFloridana"/>            
            <entity id="gce:Hydrobiidae"/>            
            <entity id="gce:GeukensiaDemissa"/>            
            <entity id="gce:PolymesodaCaroliniana"/>            
            <entity id="gce:GemmaGemma"/>            
         </sms:domain>
      </sms:measurement>
      <sms:measurement label="m5b" precision="0.01" key="no">
         <sms:characteristic id="unit:Length"/>
         <sms:standard id="unit:Millimeter"/>
      </sms:measurement>
      <sms:context observation="o4" identifying="no">
         <sms:relationship id="gce:Within"/>
      </sms:context>
      <sms:context observation="o2" identifying="no">
         <sms:relationship id="gce:Within"/>
      </sms:context>
      <sms:context observation="o6" identifying="no">
         <sms:relationship id="gce:HasPart"/>
      </sms:context>
   </sms:observation>  
  
   <!-- mapping: Mollusc -->
   <sms:map attribute="att.7" measurement="m5a" 
	   if="att.7 eq 'Littoraria'" value="LittorariaIrrorata"/>
   <sms:map attribute="att.7" measurement="m5a" 
	   if="att.7 eq 'Melampus'" value="MelampusBidentatus"/>
   <sms:map attribute="att.7" measurement="m5a" 
	   if="att.7 eq 'Detracia'" value="DetraciaFloridana"/>
   <sms:map attribute="att.7" measurement="m5a" 
	   if="att.7 eq 'Hydrobiidae'" value="Hydrobiidae"/>
   <sms:map attribute="att.7" measurement="m5a" 
	   if="att.7 eq 'Geukensia'" value="GeukensiaDemissa"/>
   <sms:map attribute="att.7" measurement="m5a" 
	   if="att.7 eq 'Polymesoda'" value="PolymesodaCaroliniana"/>
   <sms:map attribute="att.7" measurement="m5a" 
	   if="att.7 eq 'Gemma'" value="GemmaGemma"/>
   <sms:map attribute="att.8" measurement="m5b"/>

  <!-- observation: MolluscShell -->
   <sms:observation label="o6" distinct="no">
      <sms:entity id="gce:MolluscShell"/>
      <sms:measurement label="m6a" key="no">
         <sms:characteristic id="gce:ShellCondition"/>
         <sms:standard id="gce:ShellConditionCodes"/>
      </sms:measurement>
      <sms:context observation="o4" identifying="no">
         <sms:relationship id="gce:PartOf"/>
      </sms:context>
   </sms:observation>  

   <sms:map attribute="att.9" measurement="m6a"
      if="att.9 eq 0" value="ShellUndamagedCode"/>
   <sms:map attribute="att.9" measurement="m6a"
      if="att.9 eq 1" value="ShellDamagedCode"/>

</sms:annotation>

=== NCEAS/semtools/dev/sms/oboedb/test1-annot.xml
<?xml version="1.0"?>
<sms:annotation 
  xmlns:oboe="http://ecoinformatics.org/oboe/oboe.1.0beta"
  xmlns:oboe-units="http://ecoinformatics.org/oboe/oboe-units.1.0beta"
  xmlns:gce="https://code.ecoinformatics.org/code/semtools/trunk/dev/sms/examples/er-2008-examples.owl"
  xmlns:sms="http://ecoinformatics.org/sms/annotation.0.9"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://ecoinformatics.org/sms/annotation.0.9 sms-semannot.xsd"
  id="sms.1.1" emlPackage="eml.1.1" dataTable="1">
    <sms:observation label="o1" distinct="yes">
        <sms:entity id="gce:TemporalRange"/>
        <sms:measurement label="m1" key="yes">
            <sms:characteristic id="gce:Year"/>
            <sms:standard id="oboe:DateTime"/>
        </sms:measurement>
    </sms:observation>
    <sms:observation label="o2">
        <sms:entity id="gce:Tree"/>
        <sms:measurement label="m2" precision="0.1">
            <sms:characteristic id="gce:DBH"/>
            <sms:standard id="oboe-units:Centimeter"/>
        </sms:measurement>
        <sms:measurement label="m3">
            <sms:characteristic id="gce:TaxonomicTypeName"/>
            <sms:standard id="gce:ITIS"/>
        </sms:measurement>
        <sms:measurement label="m4" key="yes">
            <sms:characteristic id="oboe:EntityName"/>
            <sms:standard id="gce:LocalTreeNames"/>
        </sms:measurement>
        <sms:context observation="o1" identifying="yes">
            <sms:relationship id="gce:Within"/>
        </sms:context>
    </sms:observation>
    <sms:map attribute="yr" measurement="m1"/>
    <sms:map attribute="dbh" measurement="m2" if="dbh ge 0"/>
    <sms:map attribute="tree" measurement="m4"/>
    <sms:map attribute="spp" measurement="m3" value="Picea rubens" 
	   if="spp eq 'piru'"/>
    <sms:map attribute="spp" measurement="m3" value="Abies balsamea" 
	   if="spp eq 'abba'"/>
</sms:annotation>

=== NCEAS/semtools/dev/sms/examples/plt-gced-0409-1-1-annot.xml
<?xml version="1.0"?>

<sms:annotation
   xmlns="http://ecoinformatics.org/sms/annotation.0.9"
   xmlns:sms="http://ecoinformatics.org/sms/annotation.0.9"
   xmlns:oboe="https://code.ecoinformatics.org/code/semtools/trunk/dev/oboe/oboe.owl"
   xmlns:unit="https://code.ecoinformatics.org/code/semtools/trunk/dev/oboe/oboe-unit.owl"
   xmlns:gce="https://code.ecoinformatics.org/code/semtools/trunk/dev/oboe/oboe-gce.owl"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://ecoinformatics.org/sms/annotation.0.9 sms-semannot.xsd"
   emlPackage="eml.11.1"
   dataTable="1">

  <!-- observation: Spatial Location -->
   <sms:observation label="o1" distinct="yes">
      <sms:entity id="gce:SpatialLocation"/>
      <sms:measurement label="m1" key="yes">
         <sms:characteristic id="oboe:EntityName"/>
         <sms:standard id="gce:GCESiteNames"/>
         <sms:domain>
            <entity id="gce:DeanCreek"/>
            <entity id="gce:UGAMarineInstitute"/>
            <entity id="gce:MarshLanding"/>
         </sms:domain>
      </sms:measurement>
   </sms:observation>

  <!-- mapping: Site -->
   <sms:map attribute="att.1" measurement="m1"/>

  <!-- observation: Treatment -->
   <sms:observation label="o2" distinct="yes">
      <sms:entity id="gce:PelletizedFertilizationTreatment"/>
      <sms:measurement label="m2" key="yes">
         <sms:characteristic id="oboe:EntityType"/>
         <sms:standard id="gce:PelletizedFertilizationTreatmentTypeNames"/>
         <sms:domain>
            <entity id="gce:PelletizedFertilizationNitrogenTreatment"/>
            <entity id="gce:PelletizedFertilizationTreatmentControl"/>
         </sms:domain>
      </sms:measurement>
   </sms:observation>

  <!-- mapping: Treatment -->
   <sms:map attribute="att.3" measurement="m2"/>

  <!-- observation: Community -->
   <sms:observation label="o3" distinct="yes">
      <sms:entity id="gce:EcologicalCommunity"/>
      <sms:measurement label="m3" key="yes">
         <sms:characteristic id="oboe:EntityType"/>
         <sms:standard id="gce:CommunityTypeNames"/>
         <sms:domain>
            <entity id="gce:BorJunCommunity"/>
            <entity id="gce:SpaBorCommunity"/>
            <entity id="gce:SpaJunCommunity"/>
            <entity id="gce:SpaDisCommunity"/>
            <entity id="gce:SpaSalCommunity"/>
         </sms:domain>
      </sms:measurement>
   </sms:observation>

  <!-- mapping: Community -->
   <sms:map attribute="att.2" measurement="m3"/>

  <!-- observation: Plot -->
   <sms:observation label="o4" distinct="yes">
      <sms:entity id="gce:ReplicatePlot"/>
      <sms:measurement label="m4a" key="yes">
         <sms:characteristic id="oboe:EntityName"/>
         <sms:standard id="oboe:Ordinal"/>
      </sms:measurement>
      <sms:measurement label="m4b" key="no" value="1">
         <sms:characteristic id="unit:Area"/>
         <sms:standard id="unit:SquareMeter"/>
      </sms:measurement>
      <sms:measurement label="m4c" key="no" value="1">
         <sms:characteristic id="unit:Length"/>
         <sms:standard id="unit:Meter"/>
      </sms:measurement>
      <sms:measurement label="m4d" key="no" value="1">
         <sms:characteristic id="gce:Width"/>
         <sms:standard id="unit:Meter"/>
      </sms:measurement>
      <sms:context observation="o1" identifying="yes">
         <sms:relationship id="gce:Within"/>
      </sms:context>
      <sms:context observation="o2" identifying="yes">
         <sms:relationship id="gce:Within"/>
      </sms:context>
      <sms:context observation="o3" identifying="no">
         <sms:relationship id="gce:Within"/>
      </sms:context>
   </sms:observation>

  <!-- mapping: Plot (Replicate)-->
   <sms:map attribute="att.4" measurement="m4a"/>
  
  <!-- observation: Subplot -->
   <sms:observation label="o5" distinct="yes">
      <sms:entity id="gce:CentralSubplot"/>
      <sms:measurement label="m5a" key="no">
         <sms:characteristic id="unit:Length" value="0.5"/>
         <sms:standard id="unit:Meter"/>
      </sms:measurement>
      <sms:measurement label="m5b" key="no">
         <sms:characteristic id="gce:Width" value="0.5"/>
         <sms:standard id="unit:Meter"/>
      </sms:measurement>
      <sms:context observation="o4" identifying="yes">
         <sms:relationship id="gce:Within"/>
      </sms:context>
   </sms:observation>  

  <!-- observation: Dry weight -->
   <sms:observation label="o6" distinct="yes">
      <sms:entity id="gce:Plant"/>
      <sms:measurement label="m6a" key="yes">
         <sms:characteristic id="oboe:EntityType"/>
         <sms:standard id="gce:TaxonomicTypeNames"/>
         <sms:domain>
            <entity id="gce:JuncusRoemerianus"/>
            <entity id="gce:BorrichiaFrutescens"/>
            <entity id="gce:BatisMaritima"/>
            <entity id="gce:SpartinaAlterniflora"/>
            <entity id="gce:DistichlisSpicata"/>
            <entity id="gce:SalicorniaVirginica"/>
         </sms:domain>
      </sms:measurement>
      <sms:measurement label="m6b" precision="0.01" key="no">
         <sms:characteristic id="gce:DryWeight"/>
         <sms:standard id="gce:GramsPerSquareMeter"/>
      </sms:measurement>
      <sms:context observation="o5" identifying="yes">
         <sms:relationship id="gce:Within"/>
      </sms:context>
   </sms:observation>  
  
   <!-- mapping: species_code -->
   <sms:map attribute="att.5" measurement="m6a" 
	   if="att.5 eq 'JROM'" value="JuncusRoemerianus"/>
   <sms:map attribute="att.5" measurement="m6a" 
	   if="att.5 eq 'BFRU'" value="BorrichiaFrutescens"/>
   <sms:map attribute="att.5" measurement="m6a" 
	   if="att.5 eq 'BMAR'" value="BatisMaritima"/>
   <sms:map attribute="att.5" measurement="m6a" 
	   if="att.5 eq 'SALT'" value="SpartinaAlterniflora"/>
   <sms:map attribute="att.5" measurement="m6a" 
	   if="att.5 eq 'DSPI'" value="DistichlisSpicata"/>
   <sms:map attribute="att.5" measurement="m6a" 
	   if="att.5 eq 'SVIR'" value="SalicorniaVirginica"/>

  <!-- mapping: plant_mass_m2 -->
   <sms:map attribute="att.8" measurement="m6b"/>
</sms:annotation>
